### ISSUE TITLE
Repacking issue

### ISSUE THREAD

**Issue by docfaizal** [Navin136/Rom-Unpacker#1]
it packs the image to*.new.dat instead of *.new.dat.br, if I uncomment the brotli command which u have commented out in repack script, it will solve the issue, right?

Btw if u have any telegram handle, pls mention it here, would love to talk with u there as there are no Android kitchen available for linux and I love the minimalism of this tool.

**Comment by Navin136** [comment]
Yus. Just uncomment and use according to your wish and @navin136 in telegram for talks....
